@startuml
title UC-07: Scholarship Targeting (Sequence)
autoactivate on
actor Fdn
participant "Vertical: Edu" as Edu
participant "Vertical: Economy" as Econ
participant "Vertical: Finance" as Fin
Fdn -> Edu: FindScholars()
    Edu -> Edu: FilterMerit()
    return MeritList
    Edu -> Econ: CheckMeansTest(MeritList)
    return EligibleList
return Show(EligibleList)
Fdn -> Fin: AwardScholarships(EligibleList)
    Fin -> Fin: CreatePaymentPlan()
return Confirmation
@enduml
