@startuml
title UC-14: Disability Support (Sequence)
autoactivate on
actor Svc
participant "Geo-Vertical: Welfare" as Welfare
participant "Vertical: Health" as Health
participant "Vertical: Finance" as Fin
Svc -> Welfare: ProcessApplication(PersonID)
    Welfare -> Health: VerifyDisability(PersonID)
    return Confirmed/Rejected
    Welfare -> Welfare: DetermineBenefit()
    return BenefitPlan
    Welfare -> Fin: InitiatePayment(BenefitPlan)
    return TxID
return Approved
@enduml
