@startuml
title UC-15: Food Assistance (Activity)
|Agency|
start
:Trigger Food Relief;
|Vertical: Economy|
:Find Households Income < PovertyLine;
:Flag Food Insecure;
|Geo-Vertical: Welfare|
:Generate Distribution List;
:Verify Family Size;
:Allocated Packs;
|Agency|
:Distribute;
stop
@enduml
